# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d4a2c16640867cf5e47d2d02468dc4ebd8944db3be5c6453a3bdcced66a3685c541affca462827943be5f526bea661b167df28c1f1076542c7c350c27aebb64

test:
  secret_key_base: 7c596a507e09c867a9bc25bdc5ce46f4ad33ed4237633190471e512d3554d3b981e6aeb30eefdd2bcfe9db76575e7af0b6235e0720a6db217418e84e662ca595

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
